export{options}

var options=[
    {name:'Select A Category',
    value:null},
    {name:'Business Services',
    value:12},
    {name:'Car & Auto',
    value:10},
    {name:'Carniceria',
    value:995},
    {name:'Coffee',
    value:16},
    
    {name:'Dining',
    value:7},
    {name:'Education',
    value:3},
    {name:'Entertainment',
    value:2},
    {name:'Food',
    value:1},
    {name:'Healthcare',
    value:6},
    
    {name:'Housing',
    value:17},
    {name:'Income',
    value:4},
    {name:'Investments',
    value:8},
    {name:'Mercado',
    value:1220},
    
    {name:'Personal Care',
    value:5},
    {name:'Prestamo',
    value:1186},
    {name:'Production Costs',
    value:896},
    {name:'Restaurants',
    value:15},
    {name:'Shopping',
    value:4},
    
    {name:'Shutterstock',
    value:895},
    {name:'Taxes',
    value:13},
    {name:'Transferencias Propias',
    value:807},
    {name:'Transferwise',
    value:1185},
    {name:'Travel',
    value:11},
    {name:'Utilities',
    value:9},
    {name:'Videojuegos',
    value:1260},
]